/// Flutter icons ZeyIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ZeyIcons
///      fonts:
///       - asset: fonts/ZeyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ZeyIcons {
  ZeyIcons._();

  static const _kFontFam = 'ZeyIcons';
  static const String? _kFontPkg = null;

  static const IconData ic_copy_link = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_create_club = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_google = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_invite = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_join_club = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_members = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_money = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_person = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icv_winner = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
